HealthNet_TeamA_R2/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from HealthNet_TeamA_R2 import views
from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    url(r'^user/', include('Users.urls', namespace="user")),
    url(r'^hospital/', include('Hospital.urls', namespace="hospital")),
    url(r'^statistics/', include('Statistics.urls', namespace="statistics")),
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                             document_root=settings.MEDIA_ROOT)

Users/urls.py
__author__ = 'Zach'
from django.conf.urls import patterns, url, include
from Users import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),

    url(r'^(?P<username>\w+)/profile/$', views.profile, name='profile'),
    url(r'^home/$', views.home, name='home'),
    url(r'^(?P<username>\w+)/edit/$', views.profile_edit, name='edit'),

    url(r'^(?P<username>\w+)/contact/$', views.contact, name='contact'),
    url(r'^(?P<username>\w+)/contact/create/$', views.create_contact, name='create_contact'),
    url(r'^(?P<username>\w+)/contact/(?P<pk>\d+)/edit/$', views.contact_edit, name='edit_contact'),
    url(r'^(?P<username>\w+)/contact/(?P<pk>\d+)/details/$', views.contact_details, name='detail_contact'),

    url(r'^(?P<username>\w+)/view/(?P<patient>\w+)', views.view_patient, name='view_patient'),
    url(r'^(?P<username>\w+)/remove/(?P<pk>\d+)', views.remove_patient, name='remove_patient'),
    url(r'^(?P<username>\w+)/add/(?P<pk>\d+)', views.add_patient, name='add_patient'),
    url(r'^(?P<username>\w+)/search/', views.patient_search, name='patient_search'),

    url(r'^', include('MedicalHistory.urls', namespace="med_his")),
    )


Users/forms.py
__author__ = 'Zach'
from django import forms
from django.contrib.auth.models import User
from Users.models import Profile, PatientProfile

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = (
            'first_name',
            'middle_name',
            'last_name',
            'email',
            'home_phone_number',
            'work_phone_number',
            'cell_phone_number',
        )


class PatientProfileForm(forms.ModelForm):
    class Meta:
        model = PatientProfile
        fields = (
            'date_of_birth',
            'home_address',
        )


class EditProfile(forms.Form):
    first_name = forms.CharField(label='First Name:', widget=forms.TextInput(attrs={'class': 'form-control'}))
    middle_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    home_phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    work_phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    cell_phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))


class EditPatient(forms.Form):
    date_of_birth = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control'}))
    home_address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))



Users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from Users.forms import UserForm, ProfileForm, PatientProfileForm, EditProfile, EditPatient
from django.db import models
from Users.models import Profile, PatientProfile, DoctorProfile, NurseProfile, EmergencyContact, SecretaryProfile, \
    AdminProfile
from Hospital.models import Hospital
from MedicalHistory.models import InsurancePolicy, Prescription, Condition, TestResult
import logging

logger = logging.getLogger('general')

def home(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('user:login'))
    else:
        active_user = request.user
        if active_user.profile.role == 'Patient':
            name = active_user.profile.get_name()
        elif active_user.profile.role == 'Doctor':
            name = "Dr. " + active_user.profile.get_name()
        elif active_user.profile.role == 'Nurse':
            name = "Nurse " + active_user.profile.get_name()
        elif active_user.profile.role == "Secretary":
            name = 'Secretary' + active_user.profile.get_name()
            return render(request, 'Users/home.html', {'name': name})
        elif active_user.profile.role == 'Admin':
            name = 'Administrator, ' + active_user.profile.get_name()
            return render(request, 'Users/home.html', {'name': name})
        else:
            name = active_user.username
        return render(request, 'Users/home.html', {'name': name})



def profile(request, username):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('user:login'))
    else:
        active_user = request.user
        if active_user.profile.role == 'Patient':
            name = active_user.profile.get_name()
        elif active_user.profile.role == 'Doctor':
            name = "Dr. " + active_user.profile.get_name()
            num_patients = len(active_user.profile.doctorprofile.patient_list.all())
            hospital_list = Hospital.objects.all()
            return render(request, 'Users/Staff/Doctor/doctor_profile.html',
                          {"name": name, 'patient_num': num_patients, 'hospital_list': hospital_list})
        elif active_user.profile.role == 'Nurse':
            name = "Nurse " + active_user.profile.get_name()
            num_patients = len(active_user.profile.nurseprofile.patient_list.all())
            hospital_list = Hospital.objects.all()
            return render(request, 'Users/Staff/Nurse/profile.html',
                          {"name": name, 'patient_num': num_patients, 'hospital_list': hospital_list})
        elif active_user.profile.role == "Secretary":
            name = 'Secretary' + active_user.profile.get_name()
            hospital_list = Hospital.objects.all()
            return render(request, 'Users/Staff/Secretary/profile.html', {'name': name, 'hospital_list': hospital_list})
        elif active_user.profile.role == 'Admin':
            name = 'Administrator, ' + active_user.profile.get_name()
            hospital_list = Hospital.objects.all()
            return render(request, 'Users/Staff/Admin/profile.html', {'name': name, 'hospital_list': hospital_list})
        else:
            name = active_user.username
        return render(request, 'Users/Patient/patient_profile.html', {"name": name, 'user': active_user})


# This registers a standard user "Patient" to the web page
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = ProfileForm(data=request.POST)
        patient_profile_form = PatientProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid() and patient_profile_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            standard_profile = profile_form.save(commit=False)
            standard_profile.user = user
            standard_profile.role = 'Patient'
            standard_profile.save()
            patient_profile = patient_profile_form.save(commit=False)
            patient_profile.profile = standard_profile
            patient_profile.save()
            registered = True
            logger.info(str(user) + " has registered into HealthNet.")
        else:
            print(user_form.errors, profile_form.errors, patient_profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = ProfileForm()
        patient_profile_form = PatientProfileForm()

    return render(
        request,
        'Users/register.html',
        {
            'user_form': user_form,
            'profile_form': profile_form,
            'patient_profile_form': patient_profile_form,
            'registered': registered
        }
    )


def user_login(request):
    auth = 3
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                auth = 0
                return HttpResponseRedirect(reverse('user:home'))
            else:
                auth = 1
                return HttpResponse('Your HealthNet account is inactive.'
                                    '<a href=' + reverse('user:login') + '>Return to login?.</a>')
        else:
            print("Invalid login: {0}, {1}".format(username, password))
            auth = 2
            return render(request, 'Users/login.html', {'authenticated': auth})

    else:
        return render(request, 'Users/login.html', {'authenticated': auth})


def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')


def profile_edit(request, username):
    # Almost working need to either create another form to ignore the username and password or figure out a workaround
    # There is another issue with the html where the date has to be set every time you want to edit
    # This page is still broken with my update to the User model
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('user:login'))
    else:
        active_user = get_object_or_404(User, username=username)
        profile = Profile.objects.filter(user=active_user)
        user_profile = get_object_or_404(profile)
        if active_user.profile.role == 'Patient':

            patient_profile = PatientProfile.objects.filter(profile=user_profile)
            patient_profile = get_object_or_404(patient_profile)

            if request.method == 'POST':
                user_profile.email = request.POST.get('Email')
                user_profile.first_name = request.POST.get('FirstName')
                user_profile.middle_name = request.POST.get('MiddleName')
                user_profile.last_name = request.POST.get('LastName')
                # patient profile isn't working right still
                if request.POST.get('DateofBirth'):
                    patient_profile.date_of_birth = request.POST.get('DateofBirth')
                patient_profile.home_address = request.POST.get('HomeAddress')
                user_profile.home_phone_number = request.POST.get('HomePhone')
                user_profile.cell_phone_number = request.POST.get('WorkPhone')
                user_profile.work_phone_number = request.POST.get('CellPhone')
                user_profile.save()
                patient_profile.save()
                logger.info(str(request.user) + " has updated its profile." )
                return redirect('user:profile', username=username)

            else:
                return render(
                    request,
                    'Users/Patient/patient_edit.html',
                    {'user': active_user, 'profile': user_profile, 'patient_profile': patient_profile}
                )
        elif active_user.profile.role == 'Doctor':
            doctor_profile = DoctorProfile.objects.filter(profile=user_profile)
            doctor_profile = get_object_or_404(doctor_profile)
            hospital_list = Hospital.objects.all()

            if request.method == 'POST':
                user_profile.email = request.POST.get('Email')
                user_profile.first_name = request.POST.get('FirstName')
                user_profile.middle_name = request.POST.get('MiddleName')
                user_profile.last_name = request.POST.get('LastName')
                user_profile.home_phone_number = request.POST.get('HomePhone')
                user_profile.cell_phone_number = request.POST.get('WorkPhone')
                user_profile.work_phone_number = request.POST.get('CellPhone')
                user_profile.save()
                return redirect('user:profile', username=username)
            else:
                return render(request, 'Users/Staff/Doctor/doctor_edit.html',
                              {'user': active_user, 'profile': user_profile, 'doctor_profile': doctor_profile,
                               'hospital_list': hospital_list})
        elif active_user.profile.role == 'Nurse':
            nurse_profile = NurseProfile.objects.filter(profile=user_profile)
            nurse_profile = get_object_or_404(nurse_profile)
            hospital_list = Hospital.objects.all()

            if request.method == 'POST':
                user_profile.email = request.POST.get('Email')
                user_profile.first_name = request.POST.get('FirstName')
                user_profile.middle_name = request.POST.get('MiddleName')
                user_profile.last_name = request.POST.get('LastName')
                user_profile.home_phone_number = request.POST.get('HomePhone')

templates/Users/EmergencyContacts/contact_detail.html
<!DOCTYPE html>
<html>
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Profile{% endblock %}

{% block side_block %}

{% endblock %}

{% block body_block %}
    <div class="container-fluid">
        {% if user.is_authenticated %}

            <div class="row">
                <div class="col-md-10">


                    <div class="page-header" style="">
                        <h1>Welcome to HealthNet, {{ user.profile.get_name }}</h1>
                    </div>

                    <div class="profile-tabs">
                        <ul class="nav nav-tabs" style="">
                            <li role="presentation"><a
                                    href="{% url "user:profile" username=user.username %}">User Details</a></li>
                            <li role="presentation"><a href="{% url "user:med_his:insurance" username=user.username %}">Insurance</a>
                            </li>
                            <li role="presentation" class="active"><a
                                    href="{% url 'user:contact' username=user.username %}">Emergency
                                Contacts</a></li>
                            <li role="presentation"><a href="{% url 'user:med_his:appointments' %}">Appointments</a>
                            <li role="presentation"><a
                                    href="{% url "user:med_his:conditions" username=user.username %}">Conditions</a>
                            </li>
                            <li role="presentation"><a href="{% url "user:med_his:tests" username=user.username %}">Test
                                Results</a></li>
                            <li role="presentation"><a
                                    href="{% url "user:med_his:prescriptions" username=user.username %}">Prescriptions</a>
                            </li>
                            <li role="presentation"><a href="{% url "user:med_his:export" username=user.username %}">Export</a>
                            </li>
                        </ul>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    <a type="button" autofocus=""
                                       href="{% url "user:contact" username=user.username %}">
                                        <span class="glyphicon glyphicon-circle-arrow-left" aria-hidden="true"></span>
                                    </a>
                                    <strong>{{ contact.get_name }}</strong></h3>
                            </div>
                            <ul class="list-group">
                                <form class="form-horizontal" role="form" method="post" action=".">
                                    {% csrf_token %}

                                    <li class="list-group-item" role="tablist">
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">First Name:</label>

                                            <div class="col-sm-10">
                                                <p class="form-control-static">{{ contact.first_name }}</p>
                                            </div>
                                        </div>
                                    </li>

                                    <li class="list-group-item" role="tablist">
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">Last Name:</label>

                                            <div class="col-sm-10">
                                                <p class="form-control-static">{{ contact.last_name }}</p>
                                            </div>
                                        </div>
                                    </li>

                                    <li class="list-group-item" role="tablist">
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">Address:</label>

                                            <div class="col-sm-10">
                                                <p class="form-control-static">{{ contact.address }}</p>
                                            </div>
                                        </div>
                                    </li>

                                    <li class="list-group-item" role="tablist">
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">Home Phone:</label>

                                            <div class="col-sm-10">
                                                <p class="form-control-static">{{ contact.home_phone }}</p>
                                            </div>
                                        </div>
                                    </li>

                                    <li class="list-group-item" role="tablist">
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">Work Phone:</label>

                                            <div class="col-sm-10">
                                                <p class="form-control-static">{{ contact.work_phone }}</p>
                                            </div>
                                        </div>
                                    </li>
                                    <li class="list-group-item" role="tablist">
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">Cell Phone:</label>

                                            <div class="col-sm-10">
                                                <p class="form-control-static">{{ contact.cell_phone }}</p>
                                            </div>
                                        </div>
                                    </li>
                                    <li class="list-group-item" role="tablist">
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">Email:</label>

                                            <div class="col-sm-10">
                                                <p class="form-control-static">{{ contact.email }}</p>
                                            </div>
                                        </div>
                                    </li>
                                </form>
                            </ul>

                            <div class="col-md-1 col-md-offset-10 col-xs-offset-4">
                                <a type="button" class="btn btn-default"
                                   href="{% url "user:edit_contact" username=user.username pk=contact.pk %}">
                                    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Edit
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        {% else %}
            <script language="javascript">
                window.location.href = "/"
            </script>
        {% endif %}
{% endblock %}
</html>

templates/Users/EmergencyContacts/contacts.html
<!DOCTYPE html>
<html>
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Profile{% endblock %}

{% block side_block %}

{% endblock %}

{% block body_block %}
    <div class="container-fluid">
        <div class="page-header">
            <h1>Welcome to HealthNet, {{ user.profile.get_name }}</h1>
        </div>

        <div class="row">
            <div class="col-md-10">
                <div class="profile-tabs">
                    <ul class="nav nav-tabs" style="">
                        <li role="presentation"><a
                                href="{% url "user:profile" username=user.username %}">User Details</a></li>
                        <li role="presentation"><a href="{% url "user:med_his:insurance" username=user.username %}">Insurance</a>
                        </li>
                        <li role="presentation" class="active"><a
                                href="{% url 'user:contact' username=user.username %}">Emergency
                            Contacts</a></li>
                        <li role="presentation"><a href="{% url 'user:med_his:appointments' %}">Appointments</a>
                        <li role="presentation"><a href="{% url "user:med_his:conditions" username=user.username %}">Conditions</a>
                        </li>
                        <li role="presentation"><a href="{% url "user:med_his:tests" username=user.username %}">Test
                            Results</a></li>
                        <li role="presentation"><a href="{% url "user:med_his:prescriptions" username=user.username %}">Prescriptions</a>
                        </li>
                        <li role="presentation"><a
                                href="{% url "user:med_his:export" username=user.username %}">Export</a></li>
                    </ul>
                </div>
                <div class="panel panel-default" data-spy="scroll" data-offset="0">
                    <table class="table">
                        <thead>
                        <th></th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Phone Number</th>
                        </thead>
                        <tbody class="scoll-area">
                        {% for contact in contact_list %}
                            <tr>
                                <td><br><a type="button" class="button btn-default glyphicon glyphicon-cog"
                                           autofocus=""
                                           href="{% url "user:edit_contact" username=user.username pk=contact.pk %}"></a>
                                </td>
                                <td scope="row"><br><a
                                        href="{% url "user:detail_contact" username=user.username pk=contact.pk %}"> {{ contact.first_name }}</a>
                                </td>
                                <td><br>{{ contact.last_name }}</td>
                                <td>{{ contact.home_phone }}
                                    <br>
                                    {% if contact.work_phone %}
                                        {{ contact.work_phone }}
                                    {% else %}
                                        <br>
                                    {% endif %}
                                    <br>
                                    {% if contact.cell_phone %}
                                        {{ contact.cell_phone }}
                                    {% else %}
                                        <br>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                    <div class="col-md-1 col-md-offset-10 col-xs-offset-4">
                        <a type="button" class="btn btn-default"
                           href="{% url "user:create_contact" username=user.username %}"><span
                                class="glyphicon glyphicon-plus" aria-hidden="true">Add</span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
</html>