HealthNet_TeamA_R2/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from HealthNet_TeamA_R2 import views
from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    url(r'^user/', include('Users.urls', namespace="user")),
    url(r'^hospital/', include('Hospital.urls', namespace="hospital")),
    url(r'^statistics/', include('Statistics.urls', namespace="statistics")),
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                             document_root=settings.MEDIA_ROOT)

Hospital/urls.py
__author__ = 'Zach'
from django.conf.urls import patterns, url, include
from Hospital import views

urlpatterns = patterns('',
                       url(r'^home/$', views.hospital, name='home'),
                       url(r'^(?P<username>\w+)/detail/(?P<pk>\d+)/$', views.hospital_details, name='detail'),
                       url(r'^(?P<username>\w+)/admit/(?P<pk>\d+)/$', views.admit_patient, name='admit'),
                       url(r'^(?P<username>\w+)/discharge/(?P<pk>\d+)/$', views.discharge_patient, name='discharge'),
                       url(r'^(?P<username>\w+)/transfer/(?P<pk>\d+)/$', views.transfer_patient, name='transfer'),
                       url(r'^(?P<username>\w+)/statistics/(?P<pk>\d+)/$', views.stats, name='stats'),
)

Users/urls.py
__author__ = 'Zach'
from django.conf.urls import patterns, url, include
from Users import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),

    url(r'^(?P<username>\w+)/profile/$', views.profile, name='profile'),
    url(r'^home/$', views.home, name='home'),
    url(r'^(?P<username>\w+)/edit/$', views.profile_edit, name='edit'),

    url(r'^(?P<username>\w+)/contact/$', views.contact, name='contact'),
    url(r'^(?P<username>\w+)/contact/create/$', views.create_contact, name='create_contact'),
    url(r'^(?P<username>\w+)/contact/(?P<pk>\d+)/edit/$', views.contact_edit, name='edit_contact'),
    url(r'^(?P<username>\w+)/contact/(?P<pk>\d+)/details/$', views.contact_details, name='detail_contact'),

    url(r'^(?P<username>\w+)/view/(?P<patient>\w+)', views.view_patient, name='view_patient'),
    url(r'^(?P<username>\w+)/remove/(?P<pk>\d+)', views.remove_patient, name='remove_patient'),
    url(r'^(?P<username>\w+)/add/(?P<pk>\d+)', views.add_patient, name='add_patient'),
    url(r'^(?P<username>\w+)/search/', views.patient_search, name='patient_search'),

    url(r'^', include('MedicalHistory.urls', namespace="med_his")),
    )


Hospital/models.py
from django.db import models
from Users.models import PatientProfile, DoctorProfile, NurseProfile, AdminProfile, SecretaryProfile

# Create your models here.


class Hospital(models.Model):
    # Details of the Hospital
    name = models.CharField(max_length=100, blank=False)
    location = models.CharField(max_length=100)
    capacity = models.IntegerField()

    # Lists of all the people in the hospital
    patient_list = models.ManyToManyField(PatientProfile, blank=True, null=True)
    doctor_list = models.ManyToManyField(DoctorProfile, blank=True, null=True)
    nurse_list = models.ManyToManyField(NurseProfile, blank=True, null=True)
    admin_list = models.ManyToManyField(AdminProfile, blank=True, null=True)
    secretary_list = models.ManyToManyField(SecretaryProfile, blank=True, null=True)

    def checkin(self, patient):
        #   adds given patient to the patient list and changes their status to
        #   admitted
        self.patient_list.add(patient)
        patient.admitted = True

    def checkout(self, patient):
        #   removes given patient from the patient list and changes their
        #   status to discharged
        self.patient_list.remove(patient)
        patient.admitted = False

    def add_nurse(self, staff):
        #   Used to add a new staff member to the list
        self.nurse_list.add(staff)

    def remove_nurse(self, staff):
        #   Used to remove a staff from the list
        self.nurse_list.remove(staff)

    def add_doctor(self, doc):
        #   Used to add a doctor to the list
        self.doctor_list.add(doc)

    def remove_doctor(self, doc):
        #   used to remove a doctor from the list
        self.doctor_list.remove(doc)

    def add_admin(self, doc):
        #   Used to add a doctor to the list
        self.admin_list.add(doc)

    def remove_admin(self, doc):
        #   used to remove a doctor from the list
        self.admin_list.remove(doc)

    def add_secretary(self, doc):
        #   Used to add a doctor to the list
        self.secretary_list.add(doc)

    def remove_secretary(self, doc):
        #   used to remove a doctor from the list
        self.secretary_list.remove(doc)

    def getConditonStats(self, condition):
        return 1
        #   TODO Implement
        # Returns all of the condition that the patients have and the number of
        #   people with them

    def getPrescriptionStats(self, prescription):
        return 0
        # TODO Implement
        # Returns all of the condition that the patients have and the number of
        #   people with them


    def getPatientStats(self):
        return None
    #   TODO Implement
    #   returns the current number of patients in the hospital

    def __str__(self):
        return self.name

Hospital/forms.py
__author__ = 'Scott'

from django import forms
from Hospital.models import Hospital


class AdmitPatientQuery(forms.Form):
    error_css_class = "alert alert-danger"
    patient = forms.CharField(
        label='Patient',
        widget=forms.TextInput(
            attrs={'required': 'true', 'class': 'form-control', 'placeholder': 'Enter Username of Patient to Admit'})
        )


class DischargePatientQuery(forms.Form):
    error_css_class = "alert alert-danger"
    patient = forms.CharField(
        label='Patient',
        widget=forms.TextInput(attrs={'required': 'true', 'class': 'form-control',
                                      'placeholder': 'Enter Username of Patient to Discharge'})
        )



    #
    # class TransferPatient(forms.ModelForm):
    # class Meta:
    # model = Hospital
    # fields = (
    #             'patient_list',
    #             'from_hospital',
    #             'to_hospital',
    #         )
    #
    #
    # class StaffListModify(forms.ModelForm):
    #     class Meta:
    #         model = Hospital
    #         fields = (
    #             'doctor_list',
    #             'staff_list',
    #         )

Hospital/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from Users.forms import UserForm, ProfileForm, PatientProfileForm
from django.db import models
from Users.models import Profile, PatientProfile, DoctorProfile, NurseProfile, AdminProfile
from MedicalHistory.models import Condition, TestResult, InsurancePolicy, Prescription
from Hospital.models import Hospital
from Hospital.forms import AdmitPatientQuery, DischargePatientQuery
import logging
# TransferPatient, StaffListModify

logger = logging.getLogger('general')

#   This will display a list of all the hospitals
def hospital(request):
    hospital_list = Hospital.objects.all()
    return render(request, 'Hospital/Doctor/hospital.html', {'hospital_list': hospital_list})


#   This is a details on a select Hospital
def hospital_details(request, username, pk):
    active_user = get_object_or_404(User, username=username)
    hospital_list = Hospital.objects.all()
    curr_hospital = get_object_or_404(Hospital, pk=pk)
    num_patients = len(curr_hospital.patient_list.all())
    num_doctors = len(curr_hospital.doctor_list.all())
    num_staff = len(curr_hospital.nurse_list.all()) + len(curr_hospital.secretary_list.all()) + len(
        curr_hospital.admin_list.all())
    if active_user.profile.role == 'Doctor':
        return render(
            request,
            'Hospital/Doctor/hospital_details.html',
            {'hospital_list': hospital_list,
             'num_patients': num_patients,
             'num_doctors': num_doctors,
             'num_staff': num_staff,
             'curr_hospital': curr_hospital}
        )
    if active_user.profile.role == 'Nurse':
        return render(
            request,
            'Hospital/Nurse/hospital_details.html',
            {'hospital_list': hospital_list,
             'num_patients': num_patients,
             'num_doctors': num_doctors,
             'num_staff': num_staff,
             'curr_hospital': curr_hospital}
        )
    elif active_user.profile.role == 'Secretary':
        return render(
            request,
            'Hospital/Secretary/hospital_details.html',
            {'hospital_list': hospital_list,
             'num_patients': num_patients,
             'num_doctors': num_doctors,
             'num_staff': num_staff,
             'curr_hospital': curr_hospital}
        )
    elif active_user.profile.role == 'Admin':
        return render(
            request,
            'Hospital/Admin/hospital_details.html',
            {'hospital_list': hospital_list,
             'num_patients': num_patients,
             'num_doctors': num_doctors,
             'num_staff': num_staff,
             'curr_hospital': curr_hospital}
        )


def admit_patient(request, username, pk):
    hospital_list = Hospital.objects.all()
    active_user = get_object_or_404(User, username=username)
    curr_hospital = get_object_or_404(Hospital, pk=pk)
    patient = None
    warning = None
    added = False
    if request.method == "POST":
        form = AdmitPatientQuery(request.POST)
        if form.is_valid():
            # Currently breaks if the username doesn't exist
            try:
                query = form.cleaned_data['patient']
                user = User.objects.filter(username=query)
                patient = Profile.objects.filter(user=user)
                patient = PatientProfile.objects.get(profile=patient)
                curr_hospital.patient_list.add(patient)
                added = True
                logger.info(str(request.user) + " admitted user " + str(user) + " to "
                            + str(curr_hospital) + ".")
            except:
                warning = "Patient doesn't exist. Please try again."
        else:
            print('form errors')
    else:
        form = AdmitPatientQuery()
    if active_user.profile.role == "Doctor":
        return render(request, 'Hospital/Doctor/admit.html', {
            'form': form,
            'added': added,
            'warning': warning,
            'patient': patient,
            'curr_hospital': curr_hospital,
            'hospital_list': hospital_list})
    elif active_user.profile.role == "Nurse":
        return render(request, 'Hospital/Nurse/admit.html', {
            'form': form,
            'added': added,
            'warning': warning,
            'patient': patient,
            'curr_hospital': curr_hospital,
            'hospital_list': hospital_list})
    elif active_user.profile.role == "Admin":
        return render(request, 'Hospital/Admin/admit.html', {
            'form': form,
            'added': added,
            'warning': warning,
            'patient': patient,
            'curr_hospital': curr_hospital,
            'hospital_list': hospital_list})
    else:
        return render(request, "PermissionDenied.html")


def discharge_patient(request, username, pk):
    active_user = get_object_or_404(User, username=username)
    hospital_list = Hospital.objects.all()
    curr_hospital = get_object_or_404(Hospital, pk=pk)
    patient = None
    warning = None
    removed = False
    if request.method == "POST":
        form = DischargePatientQuery(request.POST)
        if form.is_valid():
            # Currently breaks if the username doesn't exist
            try:
                query = form.cleaned_data['patient']
                user = User.objects.filter(username=query)
                patient = Profile.objects.filter(user=user)
                patient = PatientProfile.objects.get(profile=patient)
                curr_hospital.patient_list.remove(patient)
                removed = True
                logger.info(str(request.user) + " removed user " + str(user) + " from "
                            + str(curr_hospital) + ".")
            except:
                warning = "Patient doesn't exist. Please try again."
        else:
            print(form.errors)
    else:
        form = DischargePatientQuery()

    if active_user.profile.role == "Doctor":
        return render(request, 'Hospital/Doctor/discharge.html', {
            'form': form,
            'removed': removed,
            'warning': warning,
            'patient': patient,
            'curr_hospital': curr_hospital,
            'hospital_list': hospital_list})
    elif active_user.profile.role == "Admin":
        return render(request, 'Hospital/Admin/discharge.html', {
            'form': form,
            'added': removed,
            'warning': warning,
            'patient': patient,
            'curr_hospital': curr_hospital,
            'hospital_list': hospital_list})


#
def transfer_patient(request, username, pk):
    message = None
    curr_hospital = get_object_or_404(Hospital, pk=pk)
    hospital_list = Hospital.objects.all()
    active_user = get_object_or_404(User, username=username)
    active_profile = get_object_or_404(Profile, user=active_user)
    if active_profile.role == "Doctor":
        active_doctor = get_object_or_404(DoctorProfile, profile=active_profile)
        recieving_hospitals = []
        for hospital in Hospital.objects.all():
            if hospital != curr_hospital:
                for doctor in hospital.doctor_list.all():
                    if doctor == active_doctor:
                        recieving_hospitals.append(hospital)
        transferring_hospital = get_object_or_404(Hospital, pk=pk)
        if request.method == "POST":
            hospital = get_object_or_404(Hospital, name=request.POST.get('Hospital'))
            print(hospital)
            patient = request.POST.get('Patient')
            patient = get_object_or_404(User, username=patient)
            patient = get_object_or_404(Profile, user=patient)
            patient = get_object_or_404(PatientProfile, profile=patient)
            print(patient)
            hospital.patient_list.add(patient)
            hospital.save()
            curr_hospital.patient_list.remove(patient)
            message = "successfully transfered" + patient.profile.user.username + " to " + hospital.name
        return render(request, 'Hospital/Doctor/transfer.html', {
            'message': message,
            'recieving': recieving_hospitals,
            'transfering': transferring_hospital,
            'curr_hospital': curr_hospital,
            'hospital_list': hospital_list})
    if active_profile.role == "Admin":
        active_admin = get_object_or_404(AdminProfile, profile=active_profile)
        recieving_hospitals = []
        for hospital in Hospital.objects.all():
            if hospital != curr_hospital:
                for admin in hospital.admin_list.all():
                    if admin == active_admin:
                        recieving_hospitals.append(hospital)
        transferring_hospital = get_object_or_404(Hospital, pk=pk)
        if request.method == "POST":
            hospital = get_object_or_404(Hospital, name=request.POST.get('Hospital'))
            print(hospital)
            patient = request.POST.get('Patient')
            patient = get_object_or_404(User, username=patient)
            patient = get_object_or_404(Profile, user=patient)
            patient = get_object_or_404(PatientProfile, profile=patient)
            print(patient)
            hospital.patient_list.add(patient)
            hospital.save()
            curr_hospital.patient_list.remove(patient)
            message = "successfully transfered" + patient.profile.user.username + " to " + hospital.name
        return render(request, 'Hospital/Admin/transfer.html', {
            'message': message,
            'recieving': recieving_hospitals,
            'transfering': transferring_hospital,
            'curr_hospital': curr_hospital,
            'hospital_list': hospital_list})
    else:

templates/Hospital/Admin/admit.html
<!DOCTYPE html>
<html>
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Profile{% endblock %}

{% block side_block %}

{% endblock %}

{% block body_block %}
    <div class="container-fluid"></div>
    {% if user.is_authenticated %}
        <div class="row">
        <div class="col-md-10">
            <div class="page-header" style="">
                <h1>Welcome to the HealthNet Hospital Page, {{ user.profile.get_name }}</h1>
            </div>
            <ul class="nav nav-tabs" style="max-width: 700px">
                <li role="presentation"><a
                        href="{% url "user:profile" username=user.username %}">User Profile</a></li>
                <li role="presentation"><a
                        href="{% url 'hospital:detail' username=user.username pk=curr_hospital.pk %}">Details</a>
                </li>
                {#                    <li role="presentation"><a href="{% url 'hospital:stats' username=user.username pk=curr_hospital.pk %}">Statistics</a></li>#}

                <li role="presentation" class="active"><a
                        href="{% url 'hospital:admit' username=user.username pk=curr_hospital.pk %}">Admit</a>
                </li>
                <li role="presentation"><a
                        href="{% url 'hospital:discharge' username=user.username pk=curr_hospital.pk %}">Discharge</a>
                </li>
                <li role="presentation"><a
                        href="{% url 'hospital:transfer' username=user.username pk=curr_hospital.pk %}">Transfer</a>
                </li>
                <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                        Change Hospital <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        {% for item in hospital_list %}
                            <li><a href="{% url 'hospital:detail' username=user.username pk=item.id %}">
                                {{ item.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
            <div class="well">
                {% if warning %}
                    <div class="alert alert-warning alert-dismissible" role="alert" style="max-width: 450px">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        {{ warning }}.
                    </div>
                {% endif %}
                {% if added %}
                    <div class="alert alert-success alert-dismissible" role="alert" style="max-width: 450px">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        {{ patient.get_name }} has successfully been added to {{ curr_hospital.name }}.
                    </div>
                {% endif %}

                <div class="container-fluid">
                    <div class="row">
                        <form role="form-group" method="post" action="." style="max-width: 600px; padding: 15px">
                            {% csrf_token %}
                            {{ form.as_p }}

                            <button class="btn btn-success" type="submit" style="margin-left: 500px">Admit</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>

    {% else %}
        <script language="javascript">
            window.location.href = "/"
        </script>
    {% endif %}

{% endblock %}
</html>

templates/Hospital/Admin/discharge.html
<!DOCTYPE html>
<html>
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Profile{% endblock %}

{% block side_block %}

{% endblock %}

{% block body_block %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-10">
                <div class="page-header" style="">
                    <h1>Welcome to the HealthNet Hospital Page, {{ user.profile.get_name }}</h1>
                </div>
                <ul class="nav nav-tabs" style="max-width: 700px">
                    <li role="presentation"><a
                            href="{% url "user:profile" username=user.username %}">User Profile</a></li>
                    <li role="presentation"><a
                            href="{% url 'hospital:detail' username=user.username pk=curr_hospital.pk %}">Details</a>
                    </li>
                    {#                    <li role="presentation"><a href="{% url 'hospital:stats' username=user.username pk=curr_hospital.pk %}">Statistics</a></li>#}

                    <li role="presentation"><a
                            href="{% url 'hospital:admit' username=user.username pk=curr_hospital.pk %}">Admit</a>
                    </li>
                    <li role="presentation" class="active"><a
                            href="{% url 'hospital:discharge' username=user.username pk=curr_hospital.pk %}">Discharge</a>
                    </li>
                    <li role="presentation"><a
                            href="{% url 'hospital:transfer' username=user.username pk=curr_hospital.pk %}">Transfer</a>
                    </li>
                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            Change Hospital <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            {% for item in hospital_list %}
                                <li><a href="{% url 'hospital:detail' username=user.username pk=item.id %}">
                                    {{ item.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
                <div class="well">
                    {% if warning %}
                        <div class="alert alert-warning alert-dismissible" role="alert" style="max-width: 450px">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            {{ warning }}.
                        </div>
                    {% endif %}
                    {% if removed %}
                        <div class="alert alert-success alert-dismissible" role="alert" style="max-width: 450px">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            {{ patient.get_name }} has successfully been discharged from {{ curr_hospital.name }}.
                        </div>
                    {% endif %}

                    <div class="container-fluid">
                        <div class="row">
                            <form role="form" method="post" action="." style="max-width: 600px; padding: 15px">
                                {% csrf_token %}

                                {{ form.as_p }}
                                <button class="btn btn-danger" type="submit" style="margin-left: 500px">Discharge
                                </button>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}
</html>

templates/Hospital/Admin/hospital.html
<!DOCTYPE html>
<html>
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Profile{% endblock %}

{% block side_block %}

{% endblock %}

{% block body_block %}

    {% if user.is_authenticated %}
    <div class="container-fluid"></div>
    {% if user.is_authenticated %}
        <div class="row">
        <div class="col-md-10">
        <div class="page-header" style="">
            <h1>Welcome to the HealthNet Hospital Page, {{ user.profile.get_name }}</h1>
        </div>
        <ul class="nav nav-tabs">
            <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                    Choose Hospital <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    {% for item in hospital_list %}
                        <li><a href="{% url 'hospital:detail' pk=item.id %}">
                            {{ item.name }}</a></li>
                    {% endfor %}
                </ul>
            </li>
        </ul>

    {% else %}
        <script language="javascript">
            window.location.href = "/"
        </script>
    {% endif %}

{% endblock %}
</html>

templates/Hospital/Admin/transfer.html
<!DOCTYPE html>
<html>
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Profile{% endblock %}

{% block side_block %}

{% endblock %}

{% block body_block %}
    <div class="container-fluid"></div>
    {% if user.is_authenticated %}
        <div class="row">
        <div class="col-md-10">
        <div class="page-header" style="">
            <h1>Welcome to the HealthNet Hospital Page, {{ user.profile.get_name }}</h1>
        </div>
        <ul class="nav nav-tabs" style="max-width: 700px">
            <li role="presentation"><a
                    href="{% url "user:profile" username=user.username %}">User Profile</a></li>
            <li role="presentation"><a
                    href="{% url 'hospital:detail' username=user.username pk=curr_hospital.pk %}">Details</a>
            </li>
            {#                    <li role="presentation"><a href="{% url 'hospital:stats' username=user.username pk=curr_hospital.pk %}">Statistics</a></li>#}

            <li role="presentation"><a
                    href="{% url 'hospital:admit' username=user.username pk=curr_hospital.pk %}">Admit</a>
            </li>
            <li role="presentation"><a
                    href="{% url 'hospital:discharge' username=user.username pk=curr_hospital.pk %}">Discharge</a>
            </li>
            <li role="presentation" class="active"><a
                    href="{% url 'hospital:transfer' username=user.username pk=curr_hospital.pk %}">Transfer</a>
            </li>
            <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                    Change Hospital <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    {% for item in hospital_list %}
                        <li><a href="{% url 'hospital:detail' username=user.username pk=item.id %}">
                            {{ item.name }}</a></li>
                    {% endfor %}
                </ul>
            </li>
                </ul>
        <div class="well">

        {% if warning %}
            <div class="alert alert-warning alert-dismissible" role="alert" style="max-width: 450px">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                {{ warning }}.
            </div>
        {% endif %}
        {% if removed %}
            <div class="alert alert-success alert-dismissible" role="alert" style="max-width: 450px">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                {{ patient.get_name }} has successfully been discharged from {{ curr_hospital.name }}.
            </div>
        {% endif %}

        <div class="container-fluid">
            <div class="row">
                <form role="form" method="post" action="." style="">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label class="col-sm-3 control-label">User to Transfer:</label>

                        <div class="col-sm-6">
                            <select class="form-control" name="Patient">
                                {% for item in curr_hospital.patient_list.all %}
                                    <option value="{{ item }}">{{ item.profile.user.username }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 control-label">Hospital to transfer to:</label>

                        <div class="col-sm-6">
                            <select class="form-control" name="Hospital">
                                {% for item in recieving %}
                                    <option value="{{ item.name }}">{{ item.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <button class="col-sm-offset-7 align-right btn btn-primary" type="submit" style="">Transfer</button>

                </form>
            </div>
        </div>

    {% else %}
        <script language="javascript">
            window.location.href = "/"
        </script>
    {% endif %}

{% endblock %}
</html>