HealthNet_TeamA_R2/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from HealthNet_TeamA_R2 import views
from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    url(r'^user/', include('Users.urls', namespace="user")),
    url(r'^hospital/', include('Hospital.urls', namespace="hospital")),
    url(r'^statistics/', include('Statistics.urls', namespace="statistics")),
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                             document_root=settings.MEDIA_ROOT)

Hospital/urls.py
__author__ = 'Zach'
from django.conf.urls import patterns, url, include
from Hospital import views

urlpatterns = patterns('',
                       url(r'^home/$', views.hospital, name='home'),
                       url(r'^(?P<username>\w+)/detail/(?P<pk>\d+)/$', views.hospital_details, name='detail'),
                       url(r'^(?P<username>\w+)/admit/(?P<pk>\d+)/$', views.admit_patient, name='admit'),
                       url(r'^(?P<username>\w+)/discharge/(?P<pk>\d+)/$', views.discharge_patient, name='discharge'),
                       url(r'^(?P<username>\w+)/transfer/(?P<pk>\d+)/$', views.transfer_patient, name='transfer'),
                       url(r'^(?P<username>\w+)/statistics/(?P<pk>\d+)/$', views.stats, name='stats'),
)

Users/urls.py
__author__ = 'Zach'
from django.conf.urls import patterns, url, include
from Users import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),

    url(r'^(?P<username>\w+)/profile/$', views.profile, name='profile'),
    url(r'^home/$', views.home, name='home'),
    url(r'^(?P<username>\w+)/edit/$', views.profile_edit, name='edit'),

    url(r'^(?P<username>\w+)/contact/$', views.contact, name='contact'),
    url(r'^(?P<username>\w+)/contact/create/$', views.create_contact, name='create_contact'),
    url(r'^(?P<username>\w+)/contact/(?P<pk>\d+)/edit/$', views.contact_edit, name='edit_contact'),
    url(r'^(?P<username>\w+)/contact/(?P<pk>\d+)/details/$', views.contact_details, name='detail_contact'),

    url(r'^(?P<username>\w+)/view/(?P<patient>\w+)', views.view_patient, name='view_patient'),
    url(r'^(?P<username>\w+)/remove/(?P<pk>\d+)', views.remove_patient, name='remove_patient'),
    url(r'^(?P<username>\w+)/add/(?P<pk>\d+)', views.add_patient, name='add_patient'),
    url(r'^(?P<username>\w+)/search/', views.patient_search, name='patient_search'),

    url(r'^', include('MedicalHistory.urls', namespace="med_his")),
    )


templates/Users/Staff/Nurse/patient_search.html
<!DOCTYPE html>
<html>
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Profile{% endblock %}

{% block side_block %}

{% endblock %}

{% block body_block %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-10">
                <div class="page-header" style="">
                    <h1>Welcome to HealthNet, {{ user.profile.get_name }}</h1>
                </div>
                <div class="profile-tabs">
                    <ul class="nav nav-tabs" style="">
                        <li role="presentation"><a
                                href="{% url "user:profile" username=user.username %}">User Details</a></li>
                        <li role="presentation"><a href="{% url 'user:med_his:appointments' %}">Appointments</a>
                        <li role="presentation"><a href="{% url 'user:med_his:prescriptions' username=user.username %}">Prescriptions</a>
                        </li>
                        <li role="presentation"><a href="{% url 'user:med_his:conditions' username=user.username %}">Conditions</a>
                        </li>
                        <li role="presentation" class="dropdown active"><a
                                href="{% url "user:patient_search" username=user.username %}">Patients</a></li>
                        <li role="presentation"><a
                                href="{% url 'user:med_his:tests' username=user.username %}">Tests</a></li>
                        <li role="presentation" class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                Choose Hospital <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                {% for item in hospital_list %}
                                    <li><a href="{% url 'hospital:detail' username=user.username pk=item.id %}">
                                        {{ item.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><strong> Search for patient:</strong></h3>
                        </div>
                        <div class="row">
                            <div class="panel-body container">
                                {% if error %}
                                    <div class="row">
                                        <div class="col-sm-offset-1 col-sm-4 alert alert-warning alert-dismissible"
                                             role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span></button>
                                            No user found.
                                        </div>
                                    </div>
                                {% endif %}
                                <form class="form-horizontal" role="form" method="post" action=".">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="inputSearch" class="col-sm-2 control-label">Search by
                                            Username</label>

                                        <div class="col-sm-5">
                                            <select class="form-control" name="query">
                                                {% for item in patients %}
                                                    <option value="{{ item.profile.user }}">{{ item.profile.user.username }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                        <button type="submit" class=" btn btn-primary">Search</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
</html>

templates/Users/Staff/Nurse/profile.html
<!DOCTYPE html>
<html>
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Profile{% endblock %}

{% block side_block %}

{% endblock %}

{% block body_block %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-10">
                <div class="page-header" style="">
                    <h1>Welcome to HealthNet, {{ user.profile.get_name }}</h1>
                </div>
                <div class="profile-tabs">
                    <ul class="nav nav-tabs" style="">
                        <li role="presentation" class="active"><a
                                href="{% url "user:profile" username=user.username %}">User Details</a></li>
                        <li role="presentation"><a href="{% url 'user:med_his:appointments' %}">Appointments</a>
                        <li role="presentation"><a href="{% url 'user:med_his:prescriptions' username=user.username %}">Prescriptions</a>
                        </li>
                        <li role="presentation"><a href="{% url 'user:med_his:conditions' username=user.username %}">Conditions</a>
                        </li>
                        <li role="presentation"><a href="{% url "user:patient_search" username=user.username %}">Patients</a>
                        </li>
                        <li role="presentation"><a
                                href="{% url 'user:med_his:tests' username=user.username %}">Tests</a></li>
                        <li role="presentation" class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                Choose Hospital <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                {% for item in hospital_list %}
                                    <li><a href="{% url 'hospital:detail' username=user.username pk=item.id %}">
                                        {{ item.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>{{ user.profile.get_name }}</strong></h3>
                    </div>
                    <ul class="list-group">
                        <form class="form-horizontal">

                            <li class="list-group-item" role="tablist" style="max-height: 50px">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Username:</label>

                                    <div class="col-sm-10">
                                        <p class="form-control-static">{{ user.username }}</p>
                                    </div>
                                </div>
                            </li>
                            <li class="list-group-item" role="tablist" style="max-height: 50px">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">First Name:</label>

                                    <div class="col-sm-10">
                                        <p class="form-control-static">{{ user.profile.first_name }}</p>
                                    </div>
                                </div>
                                {% if user.profile.middle_name != "" %}
                                    <li class="list-group-item" role="tablist" style="max-height: 50px">
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">Middle Name:</label>

                                            <div class="col-sm-10">
                                                <p class="form-control-static">{{ user.profile.middle_name }}</p>
                                            </div>
                                        </div>
                                    </li>
                                {% endif %}
                            <li class="list-group-item" role="tablist" style="max-height: 50px">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Last Name:</label>

                                    <div class="col-sm-10">
                                        <p class="form-control-static">{{ user.profile.last_name }}</p>
                                    </div>
                                </div>
                            </li>
                            <li class="list-group-item" role="tablist" style="max-height: 50px">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Email:</label>

                                    <div class="col-sm-10">
                                        <p class="form-control-static">{{ user.profile.email }}</p>
                                    </div>
                                </div>
                            </li>
                            {% if user.profile.home_phone_number != "" %}
                                <li class="list-group-item" role="tablist" style="max-height: 50px">
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">Home Phone:</label>

                                        <div class="col-sm-10">
                                            <p class="form-control-static">{{ user.profile.home_phone_number }}</p>
                                        </div>
                                    </div>
                                </li>
                            {% endif %}
                            <li class="list-group-item" role="tablist" style="max-height: 50px">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Work Phone:</label>

                                    <div class="col-sm-10">
                                        <p class="form-control-static">{{ user.profile.work_phone_number }}</p>
                                    </div>
                                </div>
                            </li>
                            {% if user.profile.cell_phone_number != "" %}
                                <li class="list-group-item" role="tablist" style="max-height: 50px">
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">Cell Phone:</label>

                                        <div class="col-sm-10">
                                            <p class="form-control-static">{{ user.profile.cell_phone_number }}</p>
                                        </div>
                                    </div>
                                </li>
                            {% endif %}
                            <li class="list-group-item" id="accordion" role="tablist" aria-multiselectable="true"
                                style="padding-top: 0px; padding-bottom: 0px">

                                <div class="form-group">
                                    <div class="row">
                                        <label class="col-sm-2 control-label">
                                            <a data-toggle="collapse" data-parent="#accordion"
                                               href="#collapsePatients "
                                               aria-expanded="true" aria-controls="collapsePatients"
                                               style="color: #333">
                                                Patient List:</a>
                                        </label>

                                        <div class="col-sm-10">
                                            <p></p>
                                        </div>
                                    </div>

                                    <div id="collapsePatients" class="panel-collapse collapse out"
                                         role="tablist"
                                         aria-labelledby="headingPatients">
                                        <div class="well" data-spy="scroll" data-offset="0">
                                            <table class="table">
                                                <thead>
                                                <th>First Name</th>
                                                <th>Last Name</th>
                                                <th>Username</th>
                                                </thead>
                                                <tbody class="scoll-area">
                                                {% for patient in user.profile.nurseprofile.patient_list.all %}
                                                    <tr>

                                                        <td scope="row">
                                                            <a href="{% url "user:view_patient" username=user.username patient=patient.profile.user.username %}"
                                                               style="color: #000000">
                                                                {{ patient.profile.first_name }}
                                                            </a>
                                                        </td>
                                                        <td>
                                                            <a href="{% url "user:view_patient" username=user.username patient=patient.profile.user.username %}"
                                                               style="color: #000000">
                                                                {{ patient.profile.last_name }}
                                                            </a>
                                                        </td>
                                                        <td>
                                                            <a href="{% url "user:view_patient" username=user.username patient=patient.profile.user.username %}"
                                                               style="color: #000000">
                                                                {{ patient.profile.user.username }}
                                                            </a>
                                                        </td>
                                                        </a>
                                                        <td>
                                                            <a href="{% url 'user:remove_patient' username=user.username pk=patient.pk %}">
                                                                <button type="button"
                                                                        class="button btn-default badge"
                                                                        style="border: 0; background-color: #d9534f">
                                                                    <span class="glyphicon glyphicon-minus align-right "></span>
                                                                </button>
                                                            </a>
                                                        </td>

                                                    </tr>
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </form>
                    </ul>
                    <div class="col-md-1 col-md-offset-10 col-xs-offset-4 ">
                        <a type="button" class="btn btn-default"
                           href="{% url "user:edit" username=user.username %}">
                            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Edit
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}
</html>

templates/Users/Staff/Nurse/profile_edit.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Profile{% endblock %}

{% block side_block %}

{% endblock %}

{% block body_block %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-10">
                <div class="page-header" style="">
                    <h1>Welcome to HealthNet, {{ user.profile.get_name }}</h1>
                </div>
                <div class="profile-tabs">
                    <ul class="nav nav-tabs" style="">
                        <li role="presentation" class="active"><a
                                href="{% url "user:profile" username=user.username %}">User Details</a></li>
                        <li role="presentation"><a href="{% url 'user:med_his:appointments' %}">Appointments</a>
                        <li role="presentation"><a
                                href="{% url 'user:med_his:prescriptions' username=user.username %}">Prescriptions</a>
                        </li>
                        <li role="presentation"><a
                                href="{% url 'user:med_his:conditions' username=user.username %}">Conditions</a>
                        </li>
                        <li role="presentation"><a href="{% url "user:patient_search" username=user.username %}">Patients</a>
                        </li>
                        <li role="presentation"><a
                                href="{% url 'user:med_his:tests' username=user.username %}">Tests</a>
                        </li>
                        <li role="presentation" class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                Choose Hospital <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                {% for item in hospital_list %}
                                    <li><a href="{% url 'hospital:detail' username=user.username pk=item.id %}">
                                        {{ item.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">
                                <a type="button" autofocus=""
                                   href="{% url "user:profile" username=user.username %}">
                                    <span class="glyphicon glyphicon-circle-arrow-left" aria-hidden="true"></span>
                                </a>
                                <strong>{{ user.profile.get_name }}</strong></h3>
                        </div>
                        <ul class="list-group">
                            <form class="form-horizontal" role="form" method="post" action=".">
                                {% csrf_token %}
                                <li class="list-group-item" role="tablist">
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">First Name:</label>

                                        <div class="col-sm-10">
                                            <input required="true" type="text" class="form-control"
                                                   id="inputFirstName" name="FirstName"
                                                   value="{{ user.profile.first_name }}">
                                        </div>
                                    </div>
                                </li>
                                <li class="list-group-item" role="tablist">
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">Middle Name:</label>

                                        <div class="col-sm-10">
                                            <input type="text" class="form-control" id="inputMiddleName"
                                                   name="MiddleName" value="{{ user.profile.middle_name }}">
                                        </div>
                                    </div>
                                </li>
                                <li class="list-group-item" role="tablist">
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">Last Name:</label>

                                        <div class="col-sm-10">
                                            <input required="true" type="text" class="form-control"
                                                   id="inputLastName" name="LastName"
                                                   value="{{ user.profile.last_name }}">
                                        </div>
                                    </div>
                                </li>
                                <li class="list-group-item" role="tablist">
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">Email:</label>

                                        <div class="col-sm-10">
                                            <input required="true" type="email" class="form-control" id="inputEmail"
                                                   name="Email" value="{{ user.profile.email }}">
                                        </div>
                                    </div>
                                </li>
                                <li class="list-group-item" role="tablist">
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">Home Phone:</label>

                                        <div class="col-sm-10">
                                            <input required="true" type="text" class="form-control"
                                                   id="inputHomePhone" name="HomePhone"
                                                   value="{{ user.profile.home_phone_number }}">
                                        </div>
                                    </div>
                                </li>
                                <li class="list-group-item" role="tablist">
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">Work Phone:</label>

                                        <div class="col-sm-10">
                                            <input required="false" type="text" class="form-control"
                                                   id="inputWorkPhone" name="WorkPhone"
                                                   value="{{ user.profile.work_phone_number }}">
                                        </div>
                                    </div>
                                </li>
                                <li class="list-group-item" role="tablist">
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">Cell Phone:</label>

                                        <div class="col-sm-10">
                                            <input type="text" class="form-control" id="inputCellPhone"
                                                   name="CellPhone" value="{{ user.profile.cell_phone_number }}">
                                        </div>
                                    </div>
                                </li>

                                <div class="col-md-1 col-md-offset-10 col-xs-offset-4">
                                    <button type="submit" class="btn btn-success" autofocus="">
                                        <span class="glyphicon glyphicon-save" aria-hidden="true"></span> Save
                                    </button>
                                </div>
                            </form>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
</html>